config/routes.rb
Ratespotgr::Application.routes.draw do

  resources :articles do
    resources :comments, only:  [:create]
  end

  resources :reviews do
    resources :comments, only:  [:create]
  end

  resources :users do
	  get :reviews, on: :member
  end

  resources :tags

	root to: 'static_pages#home'

  resources :sessions, only: [:new, :create, :destroy]

  match '/signup', to: 'users#new'
  match '/signin', to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

  
	match '/search', to: 'search#index'

  match '/admin', to: 'admin#index'

  get "admin/index"

  get "admin/reviews"

  get "admin/articles"

end

app/models/article.rb
# == Schema Information
#
# Table name: articles
#
#  id         :integer          not null, primary key
#  title      :string(255)
#  content    :text
#  image_url  :string(255)
#  user_id    :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Article < ActiveRecord::Base
  attr_accessible :content, :title, :image_url,  :user_id, :tag_list

  # validations
  validates :title, presence: true, length: { in: 8..60 }
  validates :content, presence: true, length: { in: 80..6000 }
  validates :image_url, presence: true, length: { in: 4..200 }
  validates :user_id, presence: true

  # scopes
  default_scope order: 'created_at DESC'
  scope :recent, order('created_at DESC').limit(10)
  scope :for_slider, order('created_at DESC').limit(3)

  # associations
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :taggings, dependent: :destroy
  has_many :tags, through: :taggings

  # callbacks
  before_save :prepare_data
  before_validation :check_if_image_url_is_valid

  def tag_list
    tags.collect do |tag|
      tag.name
    end.join(", ")
  end

  def tag_list=(tags_string)
    tag_names = tags_string.split(",").collect{|s| s.strip.downcase}.uniq # Create an array with the unique, normalized tags received
    new_or_found_tags = tag_names.collect { |name| Tag.find_or_create_by_name(name) } # Create the tags, if they don't exist
    self.tags = new_or_found_tags # and associate them with this article
  end


  private

  def check_if_image_url_is_valid
    false unless image_url.end_with?(".jpg", ".jpeg", ".png")
  end

  def prepare_data
    self.title = title.strip
    self.content = content.strip
  end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  before_filter :signed_in_user, only: [:new, :create, :edit, :update, :destroy]
  before_filter :correct_user, only: [:edit, :update, :destroy] #defines also an instance var for those
  before_filter :allowed_to_post, only: [:new, :edit, :update, :destroy, :create]

  def index
    @articles = Article.includes(:user).paginate(page: params[:page], per_page: 4)
  end

  def new
    @article = Article.new
  end

  def create
    @article = current_user.articles.build(params[:article])
    if @article.save
      flash[:success] = 'Article posted!'
      redirect_to @article
    else
      render 'new'
    end
  end

  def show
    begin
      @article = Article.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      logger.error "Attempt to access invalid review #{params[:id]}"
      redirect_to root_url, notice: 'Article does not exist'
    else
      @comment = @article.comments.build # Initializing @comment for the comments/form partial
      @comments = @article.comments.includes(:user)
    end
  end


  def edit
  end

  def update
    if @article.update_attributes(params[:article])
      redirect_to root_url
      flash[:success] = "Successful edit"
    else
      render 'edit'
    end
  end

  def destroy
    @article = Article.find(params[:id])
    if @article.destroy
      redirect_to root_url
    else
      flash[:error] = 'Failed to delete the article'
      redirect_to root_url
    end
  end


  # callbacks

  def correct_user
    @article = current_user.articles.find_by_id(params[:id]) # Check if the accessed review belongs to current user
    redirect_to root_url, notice: 'You are not authorized for that action' if @article.nil?
  end

  def allowed_to_post
    redirect_to root_url, notice: 'You are not authorized for that action' unless current_user.article_author?
  end

end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.erb
<%= form_for(@article) do |f| %>

    <%= render 'shared/error_messages', object: f.object %>

    <%= f.label :title %>
    <%= f.text_field :title %>

    <%= f.label :image_url %>
    <%= f.text_field :image_url %>

    <%= f.label :content %>
    <%= f.text_area :content %>

    <%= f.label :tag_list, "Tag list (separate with commas)" %>
    <%= f.text_field :tag_list %>

    <%= f.submit "Send", class: "btn btn-large btn-primary" %>

<% end %>

app/views/articles/_preview.erb
<div class="span4 particle_article">

  <h3 class="previewTitle"><%= link_to article.title.titleize, article %></h3>
  <%= image_tag(article.image_url, class: "particle") %>

  <p> <%= truncate(article.content, length: 200, separator: ' ') %>  </p>

  <p>by <em><%= link_to article.user.name.titleize, article.user, id: 'author' %></em><br/>
    <date><em><%= time_ago_in_words(article.created_at) %> ago</em></date>
  </p>

  <p class="commentsCount"><%= pluralize(article.comments.count, 'comment') %></p>
  <% if current_user?(article.user) %>
      <div class="userOptions">
        <%= link_to 'Edit', edit_article_path(article) %>
        <%= link_to 'Delete', article, method: :delete, confirm: 'Are you sure?' %>
      </div>
  <% end %>

</div>

app/views/articles/edit.html.erb
<% provide(:title, "Edit article") %>
<div class="span6 offset3">
  <%= render 'form' %>
</div>

app/views/articles/index.html.erb
<% provide(:title, 'Articles') %>
<div class="row-fluid">
  <div class="span12">
    <%= render partial: 'articles/preview', collection: @articles, as: :article %>
    <%= will_paginate %>
  </div>
</div>

app/views/articles/new.html.erb
<% provide(:title, "Create article") %>
<div class="span9">
  <%= render 'form' %>
</div>

app/views/articles/show.html.erb
<% provide(:title, @article.title) %>

<div class="span12">
  <h3 class="reviewTitle"><%= @article.title.titleize %></h3>
  <p>Posted <em> <%= time_ago_in_words(@article.created_at) %> ago</em></p>
  <%= image_tag @article.image_url, alt: @article.title, class: 'review' %>
  <p class="content"><%= simple_format(h @article.content) %></p>
  <hr/>
  <h4><%= gravatar_for(@article.user, size: 50) %> by <%= link_to @article.user.name.titleize, @article.user %></h4>
  <br />
  <hr/>

  <p>
    Tags:
    <% @article.tags.each do |tag| %>
        <%= link_to tag.name, tag_path(tag) %>
    <% end %>
  </p>

  <hr />

  <%= render partial: 'comments/form' %>

  <hr />

  <%= render @comments %>
</div>