config/routes.rb
Ratespotgr::Application.routes.draw do

  resources :articles do
    resources :comments, only:  [:create]
  end

  resources :reviews do
    resources :comments, only:  [:create]
  end

  resources :users do
	  get :reviews, on: :member
  end

  resources :tags

	root to: 'static_pages#home'

  resources :sessions, only: [:new, :create, :destroy]

  match '/signup', to: 'users#new'
  match '/signin', to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

  
	match '/search', to: 'search#index'

  match '/admin', to: 'admin#index'

  get "admin/index"

  get "admin/reviews"

  get "admin/articles"

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  name            :string(255)
#  email           :string(255)
#  password_digest :string(255)
#  remember_token  :string(255)
#  article_author  :boolean          default(FALSE)
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ActiveRecord::Base
  attr_accessible :email, :name, :password, :password_confirmation, :article_author

  has_secure_password

  # globals
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  ARTICLE_AUTHORS = %w[chris_maroudas@gmail.com grigoria_pont@gmail.com]   # users that are allowed to post articles

  # validations
  validates :name, presence: true, length: { maximum: 40 }
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }, exclusion: { in: %w[ratespot_admin@gmail.com]}
  validates :password, presence: true, length: { minimum: 6 }
  validates :password_confirmation, presence: true

  # associations
  has_many :reviews, dependent: :destroy
  has_many :articles, dependent: :destroy
  has_many :comments, dependent: :destroy


  # callbacks
  before_validation :prepare_email, :check_if_article_author
  before_save :create_remember_token

  after_save :send_register_email
  after_update :send_update_email


  # methods

  def admin?
    email == "ratespot_admin@gmail.com"
  end

  private

  def check_if_article_author
      self.article_author = true if ARTICLE_AUTHORS.include?(email)
  end

  def prepare_email
    self.email = email.strip.downcase if email
  end

  def create_remember_token
    self.remember_token = SecureRandom.urlsafe_base64
  end


  # Mailing

  def send_update_email
    UserMailer.updated_user(self).deliver
  end

  def send_register_email
    UserMailer.registered_user(self).deliver
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_filter :signed_in_user, only: [:show, :edit, :update, :destroy, :reviews]
  # defines the @user instance var
  before_filter :correct_user, only: [:edit, :update, :destroy]

  def new
    redirect_to root_url if signed_in?
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      flash[:success] = 'Thank you for signing up'
      redirect_to root_path
    else
      render 'new'
    end
  end

  def index
  end

  def show
    begin
      @user = User.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      logger.error "Attempt to access invalid user #{params[:id]}"
      redirect_to root_path, notice: 'User does not exist'
    end
  end

  def edit
  end

  def update
    if @user.update_attributes(params[:user])
      redirect_to root_path
      flash[:success] = 'Profile edited'
      sign_in @user
    else
      render 'edit'
    end
  end

  def destroy
    if current_user.destroy
      redirect_to root_path, notice: 'Profile deleted'
    else
      render 'show'
      flash[:error] = 'Profile failed to delete'
    end
  end

  def reviews
    @user = User.find(params[:id])
    @reviews = @user.reviews.includes(:user).paginate(page: params[:page], per_page: 6)
  end

  def correct_user
    @user = User.find(params[:id])
    redirect_to root_path, notice: "You are not authorized to do that" unless current_user?(@user)
  end

end

app/helpers/users_helper.rb
module UsersHelper

	def gravatar_for(user, options = { size: 50 })
		gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
		size = options[:size]
		gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
		image_tag(gravatar_url, alt: user.name, class: "gravatar")
	end

end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>

    <%= render 'shared/error_messages', object: f.object %>

    <%= f.label :name %>
    <%= f.text_field :name %>

    <%= f.label :email %>
    <%= f.text_field :email %>

    <%= f.label :password %>
    <%= f.password_field :password %>

    <%= f.label :password_confirmation, "Confirmation" %>
    <%= f.password_field :password_confirmation %>

    <%= f.submit "Submit", class: "btn btn-large btn-primary" %>
<% end %>

app/views/users/edit.html.erb
<% provide(:title, 'Edit profile') %>

<div class="fluid-row">
  <div class="span9">
    <%= render 'users/form' %>
  </div>
</div>

app/views/users/new.html.erb
<% provide(:title, 'Sign Up') %>
<h1>Sign up</h1>

<div class="fluid-row">
  <div class="span9">
    <%= render 'users/form' %>
  </div>
</div>

app/views/users/reviews.html.erb
<% provide(:title, 'Reviews') %>
<% if @reviews.any? %>
    <div class="row-fluid">
      <%= render partial: 'reviews/preview', collection: @reviews, as: :review %>
      <%= will_paginate @reviews %>
    </div>
<% end %>

app/views/users/show.html.erb
<div class="row-fluid">
  <div class="span12">

    <% provide(:title, @user.name.titleize) %>
    <%= gravatar_for(@user) %>
    <h2><%= @user.name.titleize %></h2>

    <h3><%= @user.email %></h3>

    <p><%= pluralize(@user.reviews.count, 'review') %>
      <%= link_to 'View them', reviews_user_path(@user) %> </p>

    <%= link_to 'Edit profile', edit_user_path(@user) %>
    <%= link_to 'Delete my profile', @user, method: :delete, confirm: 'Are you sure you want to delete your profile?' %>

  </div>
</div>