config/routes.rb
Ratespotgr::Application.routes.draw do

  resources :articles do
    resources :comments, only:  [:create]
  end

  resources :reviews do
    resources :comments, only:  [:create]
  end

  resources :users do
	  get :reviews, on: :member
  end

  resources :tags

	root to: 'static_pages#home'

  resources :sessions, only: [:new, :create, :destroy]

  match '/signup', to: 'users#new'
  match '/signin', to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

  
	match '/search', to: 'search#index'

  match '/admin', to: 'admin#index'

  get "admin/index"

  get "admin/reviews"

  get "admin/articles"

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  before_filter :signed_in_user, only: [:new, :create, :edit, :update, :destroy]
  before_filter :correct_user, only: [:edit, :update, :destroy] #defines also an instance var for those

  def new
    @review = Review.new
  end

  def create
    @review = current_user.reviews.build(params[:review])
    if @review.save
      redirect_to @review
      flash[:success] = "Thank you for your review"
    else
      render 'new'
    end
  end

  def index

    if params[:category] && params[:category].in?(%w[cpu gpu storage monitor motherboard])
      @reviews = Review.where(category: params[:category], approved: true).includes(:user).paginate(page: params[:page], per_page: 6)
    else
      @reviews = Review.where(approved: true).includes(:user).paginate(page: params[:page], per_page: 6)
    end

  end

  def edit
    #Instance var @review, defined at correct_user
  end

  def show
    begin
      @review = Review.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      logger.error "Attempt to access invalid review #{params[:id]}"
      redirect_to root_url, notice: 'Review does not exist'
    else
      @comment = @review.comments.build # Initializing @comment for the comments/form partial
      @comments = @review.comments.includes(:user)
    end
  end

  def update

    # An admin might be issuing an UPDATE
    # and in that case the @review defined in correct_user will be nil, since
    # the review doesn't belong to the current_user
    @review ||= Review.find(params[:id])

    if @review.update_attributes(params[:review])
      redirect_to @review
      flash[:success] = "Edit successful"
    else
      render 'edit'
    end
  end

  def destroy
    @review.destroy
    redirect_to root_url
    flash[:notice] = 'Review deleted'
  end


  def search
    @reviews = Review.search(params[:search])
  end


  # before filters

  def correct_user
    @review = current_user.reviews.find_by_id(params[:id]) # Check if the accessed review belongs to current user
    redirect_to root_url, notice: 'You are not authorized for that action' if @review.nil? && !current_user.admin?
  end

end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/reviews/_admin_approval_form.html.erb
<%= form_for(@review) do |f| %>

    <%= render 'shared/error_messages', object: f.object %>

    <%= f.label :approved %>
    <%= f.radio_button :approved, true %> Approved
    <%= f.radio_button :approved, false %> Rejected

    <%= f.submit "Send", class: "btn btn-large btn-primary" %>
<% end %>

app/views/reviews/_form.html.erb
<%= form_for(@review) do |f| %>

    <%= render 'shared/error_messages', object: f.object %>

    <%= f.label :title %>
    <%= f.text_field :title %>

    <%= f.label :content %>
    <%= f.text_area :content %>

    <%= f.label :category %>

    <%= f.select :category, Review::CATEGORIES.map { |category| category.titleize }, :prompt => 'Select a category' %>

    <%= f.label :product %>
    <%= f.text_field :product %>

    <%= f.label 'Rating' %>
    <%= f.radio_button :rating, 1 %> Worst thing ever
    <%= f.radio_button :rating, 2 %> Bad
    <%= f.radio_button :rating, 3 %> Average
    <%= f.radio_button :rating, 4 %> Good
    <%= f.radio_button :rating, 5 %> Excellent

    <%= f.label :image_url %>
    <%= f.text_field :image_url %>

    <%= f.submit "Send", class: "btn btn-large btn-primary" %>
<% end %>

app/views/reviews/_preview.html.erb
<div class="span6 preview_review">
  <h2 class="productTitle"><%= review.product.titleize %></h2>

  <h3 class="previewTitle"><%= link_to review.title.titleize, review %></h3>
  <%= image_tag(review.image_url, alt: review.product, class: "preview") %>

  <p> <%= truncate(review.content, length: 200, separator: ' ') %>  </p>

  <p>by <em><%= link_to review.user.name.titleize, review.user, id: 'author' %></em><br/>
    <date><em><%= time_ago_in_words(review.created_at) %> ago</em></date>
  </p>

  <p class="commentsCount"><%= pluralize(review.comments.count, 'comment') %></p>
  <% if current_user?(review.user) %>
      <div class="userOptions">
        <%= link_to 'Edit', edit_review_path(review) %>
        <%= link_to 'Delete', review, method: :delete, confirm: 'Are you sure?' %>
      </div>
  <% end %>

</div>

app/views/reviews/edit.html.erb
<% provide(:title, 'Edit review') %>

<div class="row">
  <div class="span6 offset3">
    <%= render 'form' %>
  </div>
</div>

app/views/reviews/index.html.erb
<% provide(:title, 'Reviews') %>

<div class="row-fluid">
  <ul class="categories span12">
    <li>Browse by category</li>
    <li class="category"><%= link_to 'All', reviews_path %></li>
    <li class="category"><%= link_to 'Processors', reviews_path(category: 'cpu') %></li>
    <li class="category"><%= link_to 'Graphics', reviews_path(category: 'gpu') %></li>
    <li class="category"><%= link_to 'Storage', reviews_path(category: 'storage') %></li>
    <li class="category"><%= link_to 'Motherboards', reviews_path(category: 'motherboard') %></li>
    <li class="category"><%= link_to 'Monitors', reviews_path(category: 'monitor') %></li>
  </ul>
</div>

<div class="row-fluid">
  <%= render partial: 'preview', collection: @reviews, as: :review %>
  <%= will_paginate %>
</div>

app/views/reviews/new.html.erb
<% provide(:title, "Create review") %>
<div class="fluid-row">
  <div class="span9">
	<%= render 'form' %>
  </div>
</div>

app/views/reviews/show.html.erb
<% provide(:title, @review.title) %>

<div class="span12">
  <h2 class="productTitle"><%= @review.product %></h2>

  <h3 class="reviewTitle"><%= @review.title.titleize %></h3>
  <p>Posted <em> <%= time_ago_in_words(@review.created_at) %> ago</em> in <em><%= @review.category.upcase %></em></p>
  <%= image_tag @review.image_url, alt: @review.product, class: 'review' %>
  <p class="content"><%= simple_format(h @review.content) %></p>
  <hr/>
  <h4><%= gravatar_for(@review.user, size: 50) %> by <%= link_to @review.user.name.titleize, @review.user %></h4>
  <br />
  <hr/>

  <p>
    Tags:
    <% @review.tags.each do |tag| %>
        <%= link_to tag.name, tag_path(tag) %>
    <% end %>
  </p>

  <hr />

  <%= render partial: 'comments/form' %>
  <hr />

  <%= render @comments %>

  <%= render partial: 'admin_approval_form' if current_user && current_user.admin? %>
</div>