config/routes.rb
Ratespotgr::Application.routes.draw do

  resources :articles do
    resources :comments, only:  [:create]
  end

  resources :reviews do
    resources :comments, only:  [:create]
  end

  resources :users do
	  get :reviews, on: :member
  end

  resources :tags

	root to: 'static_pages#home'

  resources :sessions, only: [:new, :create, :destroy]

  match '/signup', to: 'users#new'
  match '/signin', to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

  
	match '/search', to: 'search#index'

  match '/admin', to: 'admin#index'

  get "admin/index"

  get "admin/reviews"

  get "admin/articles"

end

app/views/layouts/_footer.html.erb
<div class="row">
  <div class="span12">
    <footer class="footer">
      <small>
        Ratespot, Copyright, 2013. All rights reserved. Made by Chris Maroudas
      </small>
    </footer>
  </div>
</div>
</div>

app/views/layouts/_header.html.erb
<header class="container top">
  <div class='row'>
    <div class="span4 search_bar">
      <%= form_tag(search_path, method: :get) do %>
          <%= text_field_tag :search, params[:search], id: 'search_field' %>
          <%= submit_tag 'Search', id: 'submit_button' %>
      <% end %>
    </div>

    <% if signed_in? %>
        <nav class='span9 user_menu'>
          <ul>
            <li><%= current_user.name.titleize %></li>
            <li><%= link_to 'My Profile', user_path(current_user) %></li>
            <li><%= link_to 'New review', new_review_path %></li>
            <li><%= link_to 'New article', new_article_path if current_user.article_author? %></li>
            <li><%= link_to 'Sign Out', signout_path, method: :delete %></li>
            <%= gravatar_for(current_user, size: 28) %>
          </ul>
        </nav>
    <% else %>
        <nav class='span3 offset5 user_menu'>
          <ul>
            <li><%= link_to 'Sign in', signin_path %></li>
            <li><%= link_to 'Sign up', signup_path %></li>
    <% end %>
    </ul>
    </nav>
  </div>
</header>

<div class="logo">
  <a href="/"><%= image_tag('ratespot.png', alt: 'Ratespot logo', class: 'logo') %></a>
</div>

app/views/layouts/_menu.html.erb
<header class="container main_menu">
  <div class='row-fluid'>
    <nav class='span12'>
      <ul>
        <li><%= link_to 'Home', root_path %></li>
        <li><%= link_to 'Reviews', reviews_path %></li>
        <li><%= link_to 'Articles', articles_path %></li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

<script type="text/javascript" src="//use.typekit.net/ixd7wzq.js"></script>
<script type="text/javascript">try{Typekit.load();}catch(e){}</script>

app/views/layouts/_sidebar.html.erb
<aside class="span3">

  <h2>Latest articles</h2>
  <% if @articles.any? %>
      <ul>
        <% @articles.each do |article| %>
            <li><%= link_to article.title, article %></li>
        <% end %>
      </ul>
  <% end %>

  <h2>Latest reviews</h2>
  <% if @reviews.any? %>
      <ul>
        <% @reviews.each do |review| %>
            <li><%= link_to review.title, review %></li>
        <% end %>
      </ul>
  <% end %>

  <h2>Tags</h2>

  <p class="tags">
    <% if @tags.any? %>
        <% @tags.each do |tag| %>
            <%= link_to tag.name, tag %>
        <% end %>
    <% end %>
  </p>

</aside>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
	<%= render 'layouts/shim'  %>
</head>
<body>

<%= render 'layouts/header' %>
<%= render 'layouts/menu' %>

<div class="container">


  <% flash.each do |key, value| %>
      <%= content_tag(:div, value, class: "alert alert-#{key}") %>
  <% end %>


  <%= yield %>



  <%= render 'layouts/footer' %>

  <h4><%= debug(params) if Rails.env.development? %></h4>
  <h4><%= debug(assigns) if Rails.env.development? %></h4>
  <h4><%= query_diet_widget if Rails.env.development? %></h4>

</div>


</body>
</html>